### PR TITLE
Added --region flag to ensure_subnet_exists

### PR DESCRIPTION
**Pull request by jmmaldonado**
Added required --region flag to the ensure_subnet_exists procedure.
Region is calculated based on the zone selected by the user when issuing the datalab create command, either by argument or by interactive selection

### CODE REVIEW

**Comment by ojarjur** [comment]
Thanks for catching this and putting in the effort to fix it.

In #2037, I am adding a [`get_region_name` method](https://github.com/googledatalab/datalab/pull/2037/files#diff-ed4811dbebc089623dd82cca13888c40R578). I think that might be a good resource to use in your fix (once that PR gets merged).

Also, `flake8` is complaining that line 773 is now too long. Can you split it across multiple lines? We can't merge until the `flake8` checks pass.

Thanks again for the help here!

**Comment by jmmaldonado** [comment]
Thanks Omar! I think I messed up pushing the wrong button before making the change to the file to pass the line length test. I am submitting the change as is, and once your PR is merged we can update the region calculation with yours ... it will be more resilient if there are changes to the zone / region naming convention

**Comment by jmmaldonado** [comment]
This fixes Issue #2054

**Comment by ojarjur** [comment]
@jmmaldonado 

> I am submitting the change as is, and once your PR is merged we can update the region calculation with yours

That's perfectly reasonable. Thanks for putting this together.

**Pull request merged**
