### PR TITLE
h5py added for non-gpu image

### PR DESCRIPTION
**Pull request by lkuligin**
Otherwise tensorflow.keras throws an error "ImportError: `save_model` requires h5py." and even prototyping is not possible.

### CODE REVIEW

**Comment by yebrahim** [comment]
With this change, does `import h5py` work in a notebook? There was an open issue about this in the past. See https://stackoverflow.com/a/43490376/1768702.

**Comment by nikhilk** [comment]
Going off the title, we should make sure the GPU image is also kept in sync.

**Comment by lkuligin** [comment]
1. yes, running `!pip install h5py`and then restarting the kernel and redoing imports helps
2. gpu image already has h5py

**Comment by chmeyers** [comment]
Re Nikhilk's comment: The GPU image already had h5py, it was one of 3 extra packages that we installed there, along with tensorflow-gpu and tflearn.  As the GPU image inherits from the non-GPU image, it will always get anything that the non-GPU image has.

**Pull request merged**
