### PR TITLE
Added Pyreadline package in Dockerfile

### PR DESCRIPTION
**Pull request by umang-sh**
Added Pyreadline in DockerFile
added to the pip install section since conda wasnt able to find it

### CODE REVIEW

**Comment by chmeyers** [comment]
pyreadline has a BSD license, so no issues there.  (https://pypi.org/project/pyreadline/)

**Comment by umang-sh** [comment]
@ojarjur Removed the Blank Line in the latest commit :)

**Comment by umang-sh** [comment]
Hi Guys,
@ojarjur @yebrahim @chmeyers 
Following up on this PR, is there anything that needs to be changed or any change in the documentation required? :)

**Comment by ojarjur** [comment]
@umang-sh Sorry for the delay getting back to you. It took me a while to track down the pyreadline license, as they put it in a subdirectory of the repository instead of the root folder (it is [here](https://github.com/pyreadline/pyreadline/blob/master/doc/COPYING) ).

There is one more thing that we need to do; copy the contents of that license file to the end of the `third_party/license.txt` file.

@umang-sh Can you take that on? Otherwise we can do it as a separate PR.

Thanks again for the contribution!

**Comment by umang-sh** [comment]
@ojarjur Sure I am gonna take the license file addition work.
I am gonna push that in the next commit (which I am gonna do shortly) 
We dont need to do a separate PR for this.
Let me make a commit in here :)

**Comment by umang-sh** [comment]
@ojarjur I took care of the license in this commit :) 
Let me know if anything else needs to be done

**Comment by umang-sh** [comment]
@ojarjur  
Pleasure :) 
Looking ahead to make some more contributions! :)

**Comment by yebrahim** [comment]
Sorry for the late follow up, I'm away now and can't build the docker image.
I'm assuming this is to fix #1176, did we test to see if this is actually adding any autocomplete functionality? I'm guessing it's not as simple as just installing the library in the image.

**Comment by ojarjur** [comment]
@yebrahim I built and checked the modified image, and autocomplete does work.

However, I then checked the currently release image (without pyreadline), and autocomplete works there too.

It looks like newer versions of Jupyter have replaced the reliance on pyreadline for autocomplete with a different package called `prompt-toolkit`... which the current Datalab image already includes.

Clearly the old issue should be closed, but there is still the question of this PR.

@umang-sh Was autocomplete the only motivation for pyreadline, or are there other reasons to want it too?

**Comment by umang-sh** [comment]
@ojarjur In addition to autocomplete pyreadline also provides following features:

keyboard text selection and copy/paste
Shift-arrowkeys for text selection
Control-c can be used for copy activate with allow_ctrl_c(True) in config file
Double tapping ctrl-c will raise a KeyboardInterrupt, use ctrl_c_tap_time_interval(x) where x is your preferred tap time window, default 0.3 s.
paste pastes first line of content on clipboard.
ipython_paste, pastes tab-separated data as list of lists or numpy array if all data is numeric
paste_mulitline_code pastes multi line code, removing any empty lines.

**Comment by ojarjur** [comment]
@umang-sh Thanks for the list. As far as I can tell, everything seems to work in our current version of the image (the one without pyreadline), *except* for double pressing <CTRL>+c sending a keyboard interrupt.

However, that doesn't work in the version with pyreadline either.

Do you know of anything current not working in the released image that this should fix?

If not, then it looks to me like pyreadline is no longer needed given the presence of prompt-toolkit.

**Comment by nikhilk** [comment]
You should avoid this.

Jupyter removed it's dependency on this. It looks unmaintained (
https://github.com/pyreadline/pyreadline?files=1) and most importantly, has
no license info apparently in the root of it's repo.

All packages added should be accounted for license info and added to our
combined file aggregating those licenses.

**Comment by umang-sh** [comment]
@ojarjur 
Indeed the things in the list are already covered (I just checked by making an image) 
Yeah pyreadline wont do much benefit

**Comment by ojarjur** [comment]
@umang-sh Thanks for checking, and thanks again for your efforts on this issue.

Sorry that this wound up not being needed, but we really appreciate the time and effort you put in to helping improve datalab.

I'm closing this PR since the library has been replaced by Jupyter.

**Comment by umang-sh** [comment]
@ojarjur 
No worries .
Whatever  it takes to make the product great :) 
I am gonna keep contributing , working on another Datalab issue now :)

**Pull request closed without merging**
